SELECT MAX(BASIC), MIN(BASIC), AVG(BASIC)
	FROM EMP
	GROUP BY DEPT_CODE;

SELECT DEPT_CODE, COUNT(*)
	FROM EMP
	WHERE SEX = 'F'
	GROUP BY DEPT_CODE;

SELECT CITY, DEPT_CODE, COUNT(*)
	FROM EMP
	GROUP BY CITY, DEPT_CODE;

SELECT DEPT_CODE, DESIG_CODE, COUNT(*)
	FROM EMP
	WHERE YEAR(JN_DT) = 2013
	GROUP BY DEPT_CODE
	ORDER BY COUNT(*) ASC;

SELECT DEPT_CODE, SUM(BASIC)
	FROM EMP
	WHERE SEX = 'M'
	GROUP BY DEPT_CODE
	HAVING SUM(BASIC) > 50000
	ORDER BY SUM(BASIC) DESC;

SELECT EMP_NAME, DESIG_DESC, BASIC
	FROM EMP, DESIGNATION
	WHERE EMP.DESIG_CODE = DESIGNATION.DESIG_CODE;

SELECT EMP_NAME, DESIG_DESC, DEPT_NAME, BASIC
	FROM EMP, DESIGNATION, DEPARTMENT
	WHERE EMP.DESIG_CODE = DESIGNATION.DESIG_CODE
	AND EMP.DEPT_CODE = DEPARTMENT.DEPT_CODE;
/*
SELECT DEPT_CODE
	FROM DEPARTMENT
	WHERE (
		SELECT COUNT(*)
			FROM EMP
			WHERE EMP.DEPT_CODE = DEPARTMENT.DEPT_CODE
	) = 0;
*/
SELECT DEPT_CODE
	FROM DEPARTMENT
	WHERE NOT EXISTS (
		SELECT *
			FROM EMP
			WHERE EMP.DEPT_CODE = DEPARTMENT.DEPT_CODE
	);

SELECT DEPT_NAME
	FROM DEPARTMENT
	WHERE DEPT_CODE IN (
		SELECT DISTINCT DEPT_CODE
			FROM EMP
	);

SELECT DEPT_NAME
	FROM DEPARTMENT
	WHERE DEPT_CODE IN (
		SELECT DEPT_CODE
			FROM EMP
			GROUP BY DEPT_CODE
			HAVING COUNT(*) >= 10
	);

SELECT DEPT_CODE
	FROM EMP
	WHERE BASIC = (
		SELECT MAX(BASIC)
			FROM EMP
	);

SELECT DESIG_DESC
	FROM DESIGNATION
	WHERE DESIG_CODE = (
		SELECT DESIG_CODE
			FROM EMP
			WHERE BASIC = (
				SELECT MAX(BASIC)
				FROM EMP
			)
	);

SELECT DEPT_CODE, COUNT(*)
	FROM EMP
	WHERE DESIG_CODE = 'MAN'
	GROUP BY DEPT_CODE;

SELECT BASIC
	FROM EMP
	WHERE BASIC >=ALL (
		SELECT BASIC
			FROM EMP
	);

SELECT BASIC
	FROM EMP
	WHERE BASIC <=ALL (
		SELECT BASIC
			FROM EMP
	);

/*
SELECT *
	FROM EMP
	GROUP BY DEPT_CODE
	HAVING SUM(BASIC) >=ALL (
		SELECT SUM(BASIC)
			FROM EMP
			GROUP BY DEPT_CODE
	);
*/

INSERT INTO EMP (
	EMP_CODE,
	EMP_NAME,
	DESIG_CODE
) VALUES (
	'AM94',
	'ARNAB MITRA',
	'X'
);

DELETE
	FROM EMP
	WHERE DESIG_CODE NOT IN (
		SELECT DISTINCT DESIG_CODE
		FROM DESIGNATION
	);

SELECT EMP_NAME
	FROM EMP AS OUTEREMP
	WHERE SEX = 'F'
	AND BASIC > (
		SELECT AVG(BASIC)
			FROM EMP AS INNEREMP
			WHERE OUTEREMP.DEPT_CODE = INNEREMP.DEPT_CODE
	);

SELECT COUNT(*)
	FROM EMP
	WHERE SEX = 'F'
		AND DESIG_CODE = 'MAN';
